version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 5
    versioning-strategy: increase-if-necessary
    labels:
      - "dependencies"
      - "javascript"
    groups:
      indirect-patch-and-minor:
        patterns:
          - "*"
        dependency-type: "indirect"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "next"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "react"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "contentlayer"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "next-contentlayer"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "eslint-config-next"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:15"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github_actions"
